name: Develop Workflow
on:
  push:
    branches:
      - develop

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - 3.9
          - 3.10
          - 3.11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: lpenz/ghaction-pytest-cov@v1
      - uses: AndreMiras/coveralls-python-action@20201129
        with:
          parallel: true
          flag-name: python-${{ matrix.python-version }}
          github-token: $ {{ secrets.GITHUB_TOKEN }}
  coverage-finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: AndreMiras/coveralls-python-action@20201129
        with:
          parallel-finished: true
